<a href="https://colab.research.google.com/github/amankhullar/cs20/blob/master/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center> <h1> CS20 Assignment 1 </h1> </center>
## Problem 1



In [9]:
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVL'] = '2'

import tensorflow as tf

sess = tf.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [0]:
sess = tf.InteractiveSession()

x = tf.random_uniform([])
y = tf.random_uniform([])

op = tf.cond(x > y, lambda : x + y, lambda : x - y)

print(sess.run(op))

1.1196562


In [0]:
x = tf.random_uniform(shape = [], minval = -1, maxval = 1, name = "x")
y = tf.random_uniform(shape = [], minval = -1, maxval = 1, name = "y")

# Using a tf.Tensor as a Python 'bool' is not allowed
# out = tf.zeros(shape = [1])

# if tf.less(x, y):
#     out = x + y
# elif tf.greater(x, y):
#     out = x - y
# else:
#     out = 0
    
def f1():
    return x + y

def f2():
    return x - y

def f3():
    return tf.zeros(shape = [1])

out = tf.case({tf.less(x, y) : f1, tf.greater(x, y) : f2}, default = f3, name = 'output', exclusive = True)
print(sess.run(out))

0.27322483


In [0]:
x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)

out = tf.equal(x, y, name = 'equal_output')

print(sess.run(out))

[[ True False False]
 [ True False False]]


In [3]:
sess = tf.InteractiveSession()

data = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
                     30.97266006,  26.67541885,  38.08450317,  20.74983215,
                     34.94445419,  34.45999146,  29.06485367,  36.01657104,
                     27.88236427,  20.56035233,  30.20379066,  29.51215172,
                     33.71149445,  28.59134293,  36.05556488,  28.66994858])

out = tf.gather(data, tf.where(tf.greater(data, 30)))

print(sess.run(out))

[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [6]:
# Numpy method of creating the diagonal matrix

# data = np.arange(1,7)
# out = np.diag(data)

# out_tf = tf.constant(out)

# print(sess.run(out_tf))

#Tensorflow method

data = tf.range(start = 1, limit = 7, name = 'range')
out = tf.linalg.diag(data, name = 'diagonal')

print(sess.run(out))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [7]:
data = tf.random_normal(shape = [10, 10], name = 'matrix')

out = tf.matrix_determinant(data, name = 'determinant')

print(sess.run(out))

-66.201225


In [8]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])

out, idx = tf.unique(x)

print(sess.run(out))

[ 5  2  3 10  6  4  1  0  9]


In [10]:
x = tf.random_normal(shape = [300], name = 'x')
y = tf.random_normal(shape = [300], name = 'y')

out = tf.cond(tf.reduce_mean(x - y) < 0, lambda : tf.losses.mean_squared_error(labels = x, predictions = y), lambda : tf.reduce_sum(tf.abs(x - y)))

print(sess.run(out))

2.150824
